# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assam_budget_board', '0003_barplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='barplot',
            name='column',
            field=models.CharField(default=b'None', max_length=50),
        ),
        migrations.AddField(
            model_name='barplot',
            name='field',
            field=models.CharField(default=b'None', max_length=200),
        ),
    ]
