# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assam_budget_board', '0003_datatable'),
        ('assam_budget_board', '0002_grantsummary'),
    ]

    operations = [
    ]
