# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('assam_budget_board', '0004_auto_20190109_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGrants',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='assam_budget_board_allgrants', serialize=False, to='cms.CMSPlugin')),
                ('url', models.URLField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='smallmultipleexpenditure',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='SmallMultipleExpenditure',
        ),
    ]
