# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assam_budget_board', '0002_balancecolumn'),
        ('assam_budget_board', '0005_auto_20190109_1718'),
    ]

    operations = [
    ]
