# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('assam_budget_board', '0005_receiptsexpenditure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allgrants',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='AllGrants',
        ),
    ]
